Force the workflow to fail in any job fails

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,9 +6,9 @@ jobs:
       matrix:
         os: ["ubuntu-24.04"]
         uv-version: ["0.11.6"]
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
+        python-version: ["3.9", 3.10, "3.11", "3.12", "3.13", "3.14"]
+      fail-fast: false
     runs-on: ${{ matrix.os }}
-    continue-on-error: true
     steps:
       - name: Checkout
         uses: actions/checkout@v6
@@ -25,3 +25,16 @@ jobs:
 
       - name: Run tests
         run: uv run ./test.py
+
+  fail-if-any-test-fails:
+    runs-on: ubuntu-latest
+    needs: test
+    if: ${{ always() }}
+    steps:
+      - name: Check matrix results
+        run: |
+          echo "Result: ${{ needs.test.result }}"
+          if [ "${{ needs.test.result }}" != "success" ]; then
+            echo "At least one matrix job failed"
+            exit 1
+          fi
